### PR TITLE
Update DBHealthView to support multiple databases.

### PR DESCRIPTION
**Pull request by cridenour**
This leverages the connections parameter to check all databases instead of just the default.

### CODE REVIEW

**Comment by abohw** [comment]
+1

**Comment by nieyka** [comment]
+1

**Comment by jayclouse** [comment]
+1

**Comment by S3D-Jake** [comment]
+1

**Comment by jakeboyles** [comment]
+1

**Comment by DavidJFelix** [comment]
Plus one

**Comment by hellogerard** [comment]
+1 C'mon man!

**Comment by DavidJFelix** [comment]
Why is this taking so long to merge?

**Comment by bifn** [comment]
+1

**Comment by jobead** [comment]
++;

**Comment by cdmwebs** [comment]
needs tests.

**Comment by hellogerard** [comment]
Alt

**Comment by ryw** [comment]
+1

**Pull request merged**
